### ISSUE TITLE
add-on crash after few hours

### ISSUE THREAD

**Issue by whncode** [sibbl/hass-lovelace-kindle-screensaver#130]
I get this errors:
```
Error: Command failed: convert: unable to open image 'output/cover.png.temp': No such file or directory @ error/blob.c/OpenBlob/3569.
convert: no decode delegate for this image format `TEMP' @ error/constitute.c/ReadImage/746.
convert: no images defined `output/cover.png' @ error/convert.c/ConvertImageCommand/3354.

    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  signal: null
}
```
after few hours of up. Watchdog failed to restart instance.

**Comment by lupino3** [comment]
Getting the same error:

```
endering http://homeassistant.local:8123/dashboard-clima/inkplate?kiosk to image...
Failed to render Error: net::ERR_CONNECTION_REFUSED at http://homeassistant.local:8123/dashboard-clima/inkplate?kiosk
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async renderUrlToImageAsync (/app/index.js:257:5)
    at async renderAndConvertAsync (/app/index.js:176:5)
Converting rendered screenshot of http://homeassistant.local:8123/dashboard-clima/inkplate?kiosk to grayscale...
/app/node_modules/gm/lib/command.js:301
          err = new Error('Command failed: ' + stderr);
                ^
Error: Command failed: convert: unable to open image 'output/cover.png.temp': No such file or directory @ error/blob.c/OpenBlob/3569.
convert: no decode delegate for this image format `TEMP' @ error/constitute.c/ReadImage/746.
convert: no images defined `output/cover.png' @ error/convert.c/ConvertImageCommand/3354.
    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  signal: null
}
```

**Comment by sibbl** [comment]
`ERR_CONNECTION_REFUSED` is an indicator that the application, i.e. the docker instance, cannot connect to `http://homeassistant.local:8123/dashboard-clima/inkplate?kiosk`.

Please check the URL and/or try it with IPs again.

**Comment by wendevlin** [comment]
I have a similar error, it happens from time to time, I havn't find a real reason. 
```
Rendering http://192.168.0.2:8123/dashboard-gast/kindle to image...
Failed to render TimeoutError: Navigation timeout of 10000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Converting rendered screenshot of http://192.168.0.2:8123/dashboard-gast/kindle to grayscale...
/app/node_modules/gm/lib/command.js:301
          err = new Error('Command failed: ' + stderr);
                ^
Error: Command failed: convert: unable to open image 'output/cover.png.temp': No such file or directory @ error/blob.c/OpenBlob/3569.
convert: no decode delegate for this image format `TEMP' @ error/constitute.c/ReadImage/746.
convert: no images defined `output/cover.png' @ error/convert.c/ConvertImageCommand/3354.
    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  signal: null
}
Node.js v18.20.1
```

Is it maybe possible to improve the error handling that it won't crash the server but it tries it again in the next round?

**Comment by color86** [comment]
Same Error since some  month :(

**Comment by flemingt** [comment]
I've got a similar issue when the screensaver docker stops overnight. Looking at my home assistant entities I can see that when the socket is active the memory usage on my server gradually increases over time, then the sticker stops and the memory usage drops. Perhaps there's a memory leak or unnecessary logging?

![Image](https://github.com/user-attachments/assets/dc7efd8f-093d-4657-9639-af86d09bda3f)
![Image](https://github.com/user-attachments/assets/4daf9e0d-0c88-4b79-9ebc-c9276a591422)

**Comment by marvhar** [comment]
Hi,

since yesterday i have the same Error "Failed to render TimoutError". Updated from last February Update to 2025.03.02 one Day befor, to 2025.03.03 today.

```
[13:50:46] INFO: Loading config...
[13:50:47] INFO: Loading additional environment variables...
[13:50:47] INFO: Using HA_BASE_URL: http://homeassistant.local:8123
[13:50:47] INFO: Starting server...
hass-lovelace-kindle-screensaver@1.0.14 start
node index.js
Starting browser...
Visiting 'http://homeassistant.local:8123' to login...
Adding authentication entry to browser's local storage...
Starting first render...
Rendering http://homeassistant.local:8123/dashboard-kindlescreens/0 to image...
Failed to render TimeoutError: Navigation timeout of 60000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Converting rendered screenshot of http://homeassistant.local:8123/dashboard-kindlescreens/0 to grayscale...
/app/node_modules/gm/lib/command.js:301
          err = new Error('Command failed: ' + stderr);
                ^
Error: Command failed: convert: unable to open image 'output/cover.png.temp': No such file or directory @ error/blob.c/OpenBlob/3569.
convert: no decode delegate for this image format `TEMP' @ error/constitute.c/ReadImage/746.
convert: no images defined `output/cover.png' @ error/convert.c/ConvertImageCommand/3354.
    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  signal: null
}
Node.js v18.20.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Watchdog trys to restart Add-On again and again.
Reinstall Add-On brings no change.

Any idea what I could try?

Thanks!

**Comment by dewoodruff** [comment]
Hi, just sharing my experience here. After upgrading to HA 2025.3.2 over the weekend I started getting the `Failed to render TimeoutError: Navigation timeout of 10000 ms exceeded` error. I had made no changes to the dashboard. 
I updated these 2 variables and it seems to be working again:
```
RENDERING_TIMEOUT=60000
RENDERING_DELAY=500
```
