### ISSUE TITLE
Connection is not possible.. 

### ISSUE THREAD

**Issue by DerPicknicker** [sibbl/hass-lovelace-kindle-screensaver#33]
Hello, 

I tried to use your Docker-Container to build an own Kindle-Display.. But sadly I cannot start your Container: 
Network is set to HOST, Token is freshly generated via HA-WebUi, its running in Portainer.. 
I attached the LOGs if you need any further information just let me know..
I checked the URL and if I open the same URL in my Browser I can open it without any issues.
<details>
  <summary>LOGs</summary>
  
  ```
 ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:148:47)
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:13)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:41)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:53)
    at /app/index.js:40:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Cannot navigate to invalid URL'
}

> hass-lovelace-kindle-screensaver@1.0.4 start
> node index.js

Starting browser...
Visiting '192.168.XXX.XXX:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:148:47)
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:13)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:41)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:53)
    at /app/index.js:40:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Cannot navigate to invalid URL'
}

> hass-lovelace-kindle-screensaver@1.0.4 start
> node index.js

Starting browser...
Visiting '192.168.XXX.XXX:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:148:47)
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:13)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:41)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:53)
    at /app/index.js:40:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Cannot navigate to invalid URL'
}

> hass-lovelace-kindle-screensaver@1.0.4 start
> node index.js

Starting browser...
Visiting '192.168.XXX.XXX:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:148:47)
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:13)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:41)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:53)
    at /app/index.js:40:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Cannot navigate to invalid URL'
}

> hass-lovelace-kindle-screensaver@1.0.4 start
> node index.js

Starting browser...
Visiting '192.168.xxx.xxx:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:148:47)
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:13)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:41)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:53)
    at /app/index.js:40:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Cannot navigate to invalid URL'
}
  ```
  
</details>

**Comment by sibbl** [comment]
@DerPicknicker please ensure that your URL starts with `http://` or `https://` 👍 I hope this helps.

**Comment by DerPicknicker** [comment]
@sibbl .. 

Many thanks for your Reply. The Container works now..
