### ISSUE TITLE
Help to debug needed

### ISSUE THREAD

**Issue by rklueber** [sibbl/hass-lovelace-kindle-screensaver#4]
Hello,

thanks for this work. I was able to jailbrake my kindle which was a long way. No I am strugglong with what I thought will be a walk in the park. I get the following error message.

Can someone point me into the right direction for trouble shooting ...

```
> hass-lovelace-kindle-screensaver@1.0.0 start /app
> node index.js

Starting browser...
Adding authentication entry to browser's local storage...
(node:285) UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_PROTOCOL_ERROR at https://10.0.10.8:8123
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /app/index.js:31:3
(node:285) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:285) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sibbl** [comment]
You probably want to configure http instead of https in front of your 10.0.10.8 IP.

**Comment by rklueber** [comment]
Hi, thanks for coming back. That's what I found out yesterday and thus closed the topic. Sorry to bother you.
