### ISSUE TITLE
Problem getting docker container to work

### ISSUE THREAD

**Issue by jendrush** [sibbl/hass-lovelace-kindle-screensaver#47]
I have Docker and Portainer installed on my Synology. I am trying to run the hass-lovelace-kindle-screensaver congener using the Web editor in Portainer. When I select the standard ports 5000:5000 I get the following errors: 

Deployment error
failed to deploy a stack: Creating network "lovelace-display_default" with the default driver Pulling app (sibbl/hass-lovelace-kindle-screensaver:latest)... Creating lovelace-display_app_1 ... Host is already in use by another container [1A[2K Creating lovelace-display_app_1 ... [31merror[0m [1B ERROR: for lovelace-display_app_1 Cannot start service app: driver failed programming external connectivity on endpoint lovelace-display_app_1 (d354b6a6fd3c42e43a1058da6bcb901307d587948ed149f0204f7a29251c6a79): Error starting userland proxy: listen tcp 0.0.0.0:5000: bind: address already in use ERROR: for app Cannot start service app: driver failed programming external connectivity on endpoint lovelace-display_app_1 (d354b6a6fd3c42e43a1058da6bcb901307d587948ed149f0204f7a29251c6a79): Error starting userland proxy: listen tcp 0.0.0.0:5000: bind: address already in use Encountered errors while bringing up the project. : exit status 1

I have 2 other containers running - Portainer and Omada controller, but it seems to me that they do not use port 5000. When I change the ports for example to 8222:8222 I get the following other errors:

Deployment error
failed to deploy a stack: Creating network "lovelace-display2_default" with the default driver Creating lovelace-display2_app_1 ... [1A[2K Creating lovelace-display2_app_1 ... [31merror[0m [1B ERROR: for lovelace-display2_app_1 Cannot start service app: Bind mount failed: '/data/compose/26/output' does not exists ERROR: for app Cannot start service app: Bind mount failed: '/data/compose/26/output' does not exists Encountered errors while bringing up the project. : exit status 1

I am a beginner in the topic of containers and I can not solve this problem, can anyone advise?

**Comment by Leticron** [comment]
Your first error message is refering to port 5000 being already in use - this is the normal synology web interface that has the standard port set to 5000 (http) and 5001 (https). 
By changing the ports to any other number than ports being used you should be fine. 

The second message is regarding the folder pathway for the output - docker can not mount the specified pathway for the container. Try using the absolute path on your synology nas which should start with /volumeX/...

**Comment by jendrush** [comment]
Gee, it was a silly question with port 5000. Thanks for the answer, tomorrow I will try to solve the problem according to your instructions.

**Comment by jendrush** [comment]
Container started, but there is error:

   
> hass-lovelace-kindle-screensaver@1.0.4 start
> node index.js
Starting browser...
Visiting 'http://192.168.2.54:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106
        return new Promise((fulfill) => (this._maximumTimer = setTimeout(fulfill, this._timeout))).then(() => new Errors_js_1.TimeoutError(errorMessage));
                                                                                                              ^
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /app/index.js:40:3

**Comment by jendrush** [comment]
I am trying to find a solution to this problem, but I have not yet succeeded. I came across some information that Puppeteer may have a problem with a particular version of headless Chrome being used.

**Comment by sibbl** [comment]
`ERR_CONNECTION_TIMED_OUT` basically tells what's going on. The docker container cannot reach your home assistant instance.

Can you SSH into your synology and try `curl http://192.168.2.54:8123` there? Some HTML of HA should be returned.
If this doesn't work, then you should check the IP + port and some other security measurements your HA instance might have configured (only allowed IP ranges for example).

If it works, then the question is why the Docker container cannot reach it. The docker container is inside its own network, which again should be bridged with the network the Synologyis in. Again, you could try to use the synology's terminal feature of the docker container to run the curl or at least a ping command inside and check what's being returned there.

**Comment by jendrush** [comment]
Thank you for the hints. I will check these things in a few hours.

**Comment by jendrush** [comment]
Thanks again for the advice. The problem was the network. The container had a bridge as a network, but it was a different pool of addresses. I temporarily set network to host, but in my case there is a conflict of port 5000 for listening with the one the Synology is running on. Is it possible to change this port to a different one?
