### ISSUE TITLE
Crash during execution

### ISSUE THREAD

**Issue by brewston** [sibbl/hass-lovelace-kindle-screensaver#52]
Recently installed RP4 with nothing else running on it.
```
root@rpi4-20230102:~# docker-compose -v   
docker-compose version 1.25.0, build unknown
root@rpi4-20230102:~# docker -v
Docker version 20.10.5+dfsg1, build 55c4c88
root@rpi4-20230102:~# uname -a
Linux rpi4-20230102 5.10.0-20-arm64 #1 SMP Debian 5.10.158-2 (2022-12-13) aarch64 GNU/Linux
root@rpi4-20230102:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
I've seen this crash a few times now : 

```
app_1  | Failed to render TimeoutError: Navigation timeout of 30000 ms exceeded
app_1  |     at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
app_1  | Converting rendered screenshot of http://192.168.0.99:8123/dashboard-kindle/kindle?kiosk to grayscale png...
app_1  | /app/node_modules/gm/lib/command.js:301
app_1  |           err = new Error('Command failed: ' + stderr);
app_1  |                 ^
app_1  | 
app_1  | Error: Command failed: convert: unable to open image '/output/cover.png.temp': No such file or directory @ error/blob.c/OpenBlob/3570.
app_1  | convert: no decode delegate for this image format `TEMP' @ error/constitute.c/ReadImage/741.
app_1  | convert: no images defined `/output/cover.png' @ error/convert.c/ConvertImageCommand/3342.
app_1  | 
app_1  |     at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
app_1  |     at ChildProcess.emit (node:events:513:28)
app_1  |     at maybeClose (node:internal/child_process:1100:16)
app_1  |     at Socket.<anonymous> (node:internal/child_process:458:11)
app_1  |     at Socket.emit (node:events:513:28)
app_1  |     at Pipe.<anonymous> (node:net:301:12) {
app_1  |   code: 1,
app_1  |   signal: null
app_1  | }
hass-lovelace-kindle-screensaver_app_1 exited with code 1
```

I should note that I had to change 3.8 to 3.7 in my docker compose file, otherwise I get this : 

```
root@rpi4-20230102:~/hass-lovelace-kindle-screensaver# docker-compose up       
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
LMK what else you might need. Thanks.

**Comment by brewston** [comment]
RENDERING_TIMEOUT=50000 seems to have helped, I will monitor it.

**Comment by sibbl** [comment]
It indeed crashes when there was no image rendered yet. So once the timeout was high enough to render something, it didn't crash anymore. I'll try to fix this soon, as it currently might cause quite a crash loop.
