### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by petrichmate** [sibbl/hass-lovelace-kindle-screensaver#54]
Hi, 

thanks for your great job.  I have some issues at logging in after the installation. Maybe I made a copy paste mistake with the token? Or is it some other issue?

Here is the log:

node index.js
Starting browser...
Visiting 'https://192.168.0.231:8123' to login...
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155
                    ? new Error(`${response.errorText} at ${url}`)
                      ^
**Error: net::ERR_CERT_COMMON_NAME_INVALID** at https://192.168.0.231:8123
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /app/index.js:40:3

**Comment by sibbl** [comment]
Thanks for your feedback!

`ERR_CERT_COMMON_NAME_INVALID`  sounds like the common name in the HTTPS certificate doesn't match the used domain. Are you maybe using a self signed ssl certificate or something? I'm afraid this may currently be not supported.

**Comment by sibbl** [comment]
Thanks for your positive feedback 👍 

`ERR_CERT_COMMON_NAME_INVALID` means that the common name in the certificate doesn't match the domain (which in your case doesn't exist, since you're using an IP).

I guess changing `https://` to `http://` will fix it.

**Comment by petrichmate** [comment]
ok, I'll investigate it further. Thank you for you fast reply, have a nice day ;)
